ValaisBooking/ValaisBooking/Models/GetReservationsViewModel.cs
using DataTransferObject;
using System.Collections.Generic;

namespace ValaisBooking.Models
{
    /// <summary>
    ///     The GetReservationsViewModel class wraps the reservation information in a model to be able to easily display or use them
    /// </summary>
    public class GetReservationsViewModel
    {
        /// <summary>
        ///     Constructor of the GetReservationsViewModel class
        /// </summary>
        public GetReservationsViewModel() { }

        /// <summary>
        ///     Constructor of the GetReservationsViewModel class
        /// </summary>
        /// <param name="reservations">
        ///     A list of Reservation objects
        /// </param>
        /// <param name="rooms">
        ///     A list of Room objects
        /// </param>
        public GetReservationsViewModel(List<Reservation> reservations, List<Room> rooms)
        {
            Reservations = reservations;
            Rooms = rooms;
        }

        /// <value>A list of Reservation objects</value>
        public List<Reservation> Reservations { get; set; }

        /// <value>A list of Room objects</value>
        public List<Room> Rooms { get; set; }

        /// <summary>
        ///     Format the Type property of the given room to a meaningful text format
        /// </summary>
        /// <param name="room">
        ///     A Room object
        /// </param>
        /// <returns>
        ///     The Type property as a meaningful text
        /// </returns>
        public static string DisplayTextForRoomType(Room room)
        {
            string displayText = room.Type switch
            {
                1 => "Simple room",
                2 => "Double room",
                _ => "Big room",
            };

            return displayText;
        }

    }
}

ValaisBooking/ValaisBooking/Controllers/HotelController.cs
using BusinessLogicLayer;
using DataTransferObject;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using ValaisBooking.Models;

namespace ValaisBooking.Controllers
{
    /// <summary>
    ///     The HotelContoller class manages URLs relating to the hotels <c>/Hotel/[...]</c>
    /// </summary>
    public class HotelController : Controller
    {
        /// <value>The HotelManager object from the Business Logic Layer that retrieves all information relating to the hotels</value>
        private IHotelManager HotelManager { get; }

        /// <value>The RoomManager object from the Business Logic Layer that retrieves all information relating to the hotel rooms</value>
        private IRoomManager RoomManager { get; }

        /// <value>The PictureManager object from the Business Logic Layer that retrieves all information relating to the room prictures</value>
        private IPictureManager PictureManager { get; }

        /// <summary>
        ///     Constructor of the HotelController class
        /// </summary>
        /// <param name="hotelManager">
        ///     The HotelManager object from the Business Logic Layer that retrieves all information relating to the hotels
        /// </param>
        /// <param name="roomManager">
        ///     The RoomManager object from the Business Logic Layer that retrieves all information relating to the rooms
        /// </param>
        /// <param name="pictureManager">
        ///     The PictureManager object from the Business Logic Layer that retrieves all information relating to the room prictures
        /// </param>
        public HotelController(IHotelManager hotelManager, IRoomManager roomManager, IPictureManager pictureManager)
        {
            HotelManager = hotelManager;
            RoomManager = roomManager;
            PictureManager = pictureManager;
        }

        /// <summary>
        ///     Manage calls to the URLs <c>/Hotel/</c> or <c>/Hotel/Index</c> with a GET request
        /// </summary>
        /// <returns>
        ///     The Index view of Hotel
        /// </returns>
        public ActionResult Index()
        {
            List<Hotel> hotels = HotelManager.GetAllHotels();
            return View(hotels);
        }

        /// <summary>
        ///     Manage calls to the URL <c>/Hotel/GetHotels/[...]</c> with a GET request
        /// </summary>
        /// <param name="searchHotelsViewModel">
        ///     The ViewModel that store search information to find hotels
        /// </param>
        /// <returns>
        ///     The GetHotels view of Hotel for the given search information stored inside the <c>SearchHotelsViewModel</c> object
        /// </returns>
        [HttpGet]
        public IActionResult GetHotels(SearchHotelsViewModel searchHotelsViewModel)
        {
            DateTime checkIn = searchHotelsViewModel.CheckIn;
            DateTime checkOut = searchHotelsViewModel.CheckOut;


            if (DateTime.Equals(checkIn, default(DateTime)))
            {
                ModelState.ClearValidationState("searchHotelsViewModel.CheckIn");
                ModelState.AddModelError("searchHotelsViewModel.CheckIn", "Check In is required");
            }
            else if (checkIn.Date < DateTime.Now.Date)
            {
                ModelState.AddModelError("searchHotelsViewModel.CheckIn", "Check In cannot be before today");
            }

            if (DateTime.Equals(checkOut, default(DateTime)))
            {
                ModelState.ClearValidationState("searchHotelsViewModel.CheckOut");
                ModelState.AddModelError("searchHotelsViewModel.CheckOut", "Check Out is required");
            }
            else if (checkOut.Date < DateTime.Now.AddDays(1).Date)
            {
                ModelState.AddModelError("searchHotelsViewModel.CheckOut", "Check Out cannot be before tomorrow");
            }

            if (checkOut.Date < checkIn.Date)
            {
                ModelState.AddModelError("searchHotelsViewModel.CheckOut", "Check out date cannot be before check in date");
            }

            if (!ModelState.IsValid)
            {
                GetHotelsViewModel invalidStateGetHotelsViewModel = new GetHotelsViewModel(searchHotelsViewModel, null);

                return View(invalidStateGetHotelsViewModel);
            }

            ViewData["showBookButton"] = true;

            string destination = searchHotelsViewModel.Destination;
            bool hasWifi = searchHotelsViewModel.HasWifi;
            bool hasParking = searchHotelsViewModel.HasParking;
            List<bool> categories = searchHotelsViewModel.Stars;
            bool hasTV = searchHotelsViewModel.HasTV;
            bool hasHairDryer = searchHotelsViewModel.HasHairDryer;
            int minPrice = 0;
            int maxPrice = searchHotelsViewModel.MaxPrice;
            bool simpleRoom = searchHotelsViewModel.SimpleRoom;
            bool doubleRoom = searchHotelsViewModel.DoubleRoom;

            List<Hotel> hotels = HotelManager.GetHotels(destination, checkIn, checkOut, hasWifi, hasParking, categories, hasTV, hasHairDryer, minPrice, maxPrice, simpleRoom, doubleRoom);

            if (hotels != null)
            {
                HttpContext.Session.SetString("destination", destination);
                HttpContext.Session.SetString("checkIn", checkIn.ToString());
                HttpContext.Session.SetString("checkOut", checkOut.ToString());
                HttpContext.Session.SetInt32("hasTV", hasTV ? 1 : 0);
                HttpContext.Session.SetInt32("hasHairDryer", hasHairDryer ? 1 : 0);
                HttpContext.Session.SetInt32("maxPrice", maxPrice);
                HttpContext.Session.SetInt32("simpleRoom", simpleRoom ? 1 : 0);
                HttpContext.Session.SetInt32("doubleRoom", doubleRoom ? 1 : 0);
            }

            GetHotelsViewModel getHotelsViewModel = new GetHotelsViewModel(searchHotelsViewModel, hotels);

            return View(getHotelsViewModel);
        }

        /// <summary>
        ///     This method shows the Details view of an hotel for the given hotel id
        ///     Manage calls to the URL <c>/Hotel/Details/[...]</c> with a GET request
        /// </summary>
        /// <param name="id">
        ///     The hotel id
        /// </param>
        /// <param name="hasTV">
        ///     A boolean value to say if the rooms must have a TV
        /// </param>
        /// <param name="hasHairDryer">
        ///     A boolean value to say if the rooms must have a hair dryer
        /// </param>
        /// <param name="maxPrice">
        ///     The maximum price of the rooms
        /// </param>
        /// <param name="simpleRoom">
        ///     A boolean value to say if the rooms must be simple rooms
        /// </param>
        /// <param name="doubleRoom">
        ///     A boolean value to say if the rooms must be double rooms
        /// </param>
        /// <param name="checkIn">
        ///     The date from which the rooms must be free
        /// </param>
        /// <param name="checkOut">
        ///     The date until which the rooms must be free
        /// </param>
        /// <returns>
        ///     The Details view of Hotel for the given search information and filters
        /// </returns>
        public ActionResult Details(int id, bool hasTV, bool hasHairDryer, int maxPrice, bool simpleRoom, bool doubleRoom, DateTime checkIn, DateTime checkOut)
        {
            Hotel hotel = HotelManager.GetHotel(id);

            if (hotel == null)
            {
                return View("Error", new ErrorViewModel { RequestId = id.ToString() });
            }

            List<Room> rooms = null;
            List<List<Picture>> picturesByRoom = null;

            if (checkIn != default(DateTime) && checkIn != null && checkOut != default(DateTime) && checkOut != null)
            {
                int minPrice = 0;

                rooms = RoomManager.GetAvailableRoomsByHotel(id, checkIn, checkOut, hasTV, hasHairDryer, minPrice, maxPrice, simpleRoom, doubleRoom);
                ViewData["checkInDate"] = checkIn.ToString("dd.MM.yyyy");
                ViewData["checkOutDate"] = checkOut.ToString("dd.MM.yyyy");

                bool mustIncreasePrice = HotelManager.IsOccupancyOver(70, id, checkIn, checkOut);

                if(rooms != null)
                {
                    if (mustIncreasePrice)
                    {
                        foreach (Room room in rooms)
                        {
                            room.Price *= (decimal)1.2;
                        }
                    }
                } 
            }
            else
            {
                rooms = RoomManager.GetRoomsByHotel(id);
            }

            if (rooms != null)
            {
                picturesByRoom = new List<List<Picture>>();

                foreach (Room room in rooms)
                {
                    List<Picture> pictures = PictureManager.GetPicturesByRoom(room.IdRoom);

                    picturesByRoom.Add(pictures);
                }
            }

            HotelDetailsViewModel hotelRoomsViewModel = new HotelDetailsViewModel(hotel, rooms, picturesByRoom);

            return View(hotelRoomsViewModel);
        }
    }
}

ValaisBooking/ValaisBooking/Controllers/RoomController.cs
using BusinessLogicLayer;
using DataTransferObject;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using ValaisBooking.Models;

namespace ValaisBooking.Controllers
{
    /// <summary>
    /// The RoomController class manages URLs relating to the room <c>/Room/[...]</c>
    /// </summary>
    public class RoomController : Controller
    {
        /// <value>The RoomManager object from the Business Logic Layer that retrieves all information relating to the hotel rooms</value>
        private IRoomManager RoomManager { get; }

        /// <value>The PictureManager object from the Business Logic Layer that retrieves all information relating to the room prictures</value>
        private IPictureManager PictureManager { get; }

        /// <summary>
        ///     Constructor of the RoomController class
        /// </summary>
        /// <param name="roomManager">
        ///     The RoomManager object from the Business Logic Layer that retrieves all information relating to the rooms
        /// </param>
        /// <param name="pictureManager">
        ///     The PictureManager object from the Business Logic Layer that retrieves all information relating to the room prictures
        /// </param>
        public RoomController(IRoomManager roomManager, IPictureManager pictureManager)
        {
            RoomManager = roomManager;
            PictureManager = pictureManager;
        }

        /// <summary>
        ///     This method shows the Details View of a room for the given room id
        ///     It manages calls to the URL <c>/Room/Details/[...]</c> with a GET request
        /// </summary>
        /// <param name="id">
        ///     The room id
        /// </param>
        /// <returns>
        ///     The Details View fr the given roomDetails ViewModel
        /// </returns>
        [HttpGet]
        public IActionResult Details(int id)
        {
            Room room = RoomManager.GetRoom(id);

            List<Picture> pictures = null;

            if(room != null)
            {
                pictures = new List<Picture>();

                pictures = PictureManager.GetPicturesByRoom(id);
            }

            RoomDetailsViewModel roomDetailsViewModel = new RoomDetailsViewModel(room, pictures);

            return View(roomDetailsViewModel);
        }

    }
}

ValaisBooking/ValaisBooking/Views/Reservation/AddReservation.cshtml
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "AddReservation";
}

<div class="alert alert-success" role="alert">
    Your reservation, No @Context.Session.GetInt32("numReservation"), was successfully made !
</div>

@{ int hotelBooked = (int)Context.Session.GetInt32("hotelBooked");
    int hasTV = (int)Context.Session.GetInt32("hasTV");
    int hasHairDryer = (int)Context.Session.GetInt32("hasHairDryer");
    string hasTVString = "False";
    if (hasTV == 1)
    {
        hasTVString = "True";
    }
    string hasHairDryerString = "False";
    if (hasHairDryer == 1)
    {
        hasHairDryerString = "True";
    }
    int maxPrice = (int)Context.Session.GetInt32("maxPrice");
    int simpleRoom = (int)Context.Session.GetInt32("simpleRoom");
    int doubleRoom = (int)Context.Session.GetInt32("doubleRoom");
    string simpleRoomString = "False";
    if (simpleRoom == 1)
    {
        simpleRoomString = "True";
    }
    string doubleRoomString = "False";
    if (doubleRoom == 1)
    {
        doubleRoomString = "True";
    }
    DateTime checkIn = Convert.ToDateTime(Context.Session.GetString("checkIn"));
    DateTime checkOut = Convert.ToDateTime(Context.Session.GetString("checkOut"));
    int numReservation = (int)Context.Session.GetInt32("numReservation");
    string firstname = Context.Session.GetString("firstname");
    string lastname = Context.Session.GetString("lastname");}

<center>
    <a href="@Url.Action("Details", "Hotel", new { id = hotelBooked, hasTV = hasTVString, hasHairDryer = hasHairDryerString, maxPrice = maxPrice, simpleRoom = simpleRoomString, doubleRoom = doubleRoomString, checkIn = checkIn, checkOut = checkOut})" class="btn btn-primary">Book more</a>
    <a href="@Url.Action("GetReservations", "Reservation", new { reservationNumber = numReservation, firstname = firstname, lastname = lastname})" class="btn btn-primary">Check my reservation</a>
</center>

ValaisBooking/ValaisBooking/Views/Reservation/GetReservations.cshtml
@using DataTransferObject;

@model GetReservationsViewModel

@{
    ViewData["Title"] = "GetReservations";
}

@{int nbReservations = Model.Reservations.Count();}

<div>
    <center>
        <h4>
            Reservation No. @Html.DisplayFor(model => model.Reservations[0].ReservationNumber)
            for @Html.DisplayFor(model => model.Reservations[0].Firstname) @Html.DisplayFor(model => model.Reservations[0].Lastname)
        </h4>
        <hr />
    </center>

    @if (ViewData["deleteConfirmed"] != null)
    {
        <div class="alert alert-success" role="alert">
            The reservation was canceled !
        </div>
    }

    <div class="mt-3">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="text-center align-middle">Housing type</th>
                    <th class="text-center align-middle">Arrival - Departure</th>
                    <th class="text-center align-middle"></th>
                </tr>
            </thead>
            <tbody>
                @for (int reservationIndex = 0; reservationIndex < nbReservations; reservationIndex++)
                {
                    Reservation reservation = Model.Reservations[reservationIndex];
                    Room room = Model.Rooms[reservationIndex];

                    <tr>
                        <td class="text-center align-middle">@GetReservationsViewModel.DisplayTextForRoomType(room)</td>
                        <td class="text-center align-middle">@Html.DisplayFor(model => reservation.CheckIn) - @Html.DisplayFor(model => reservation.CheckOut)</td>
                        <td class="text-center align-middle">
                            <a href="@Url.Action("Details", "Room", new { id = reservation.Room_IdRoom })" class="btn btn-primary mr-2">See Room</a>
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#cancelModal@(reservation.IdReservation)">
                                Cancel Reservation
                            </button>
                            <div class="modal fade" id="cancelModal@(reservation.IdReservation)" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="cancelModalLabel@(reservation.IdReservation)" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="cancelModalLabel@(reservation.IdReservation)">Cancel Reservation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to cancel your reservation ?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                            <form method="POST" asp-action="Delete" asp-controller="Reservation">
                                                <input type="hidden" name="id" value="@reservation.IdReservation" />
                                                <input type="hidden" name="numReservation" value="@reservation.ReservationNumber" />
                                                <input type="hidden" name="firstname" value="@reservation.Firstname" />
                                                <input type="hidden" name="lastname" value="@reservation.Lastname" />
                                                <button type="submit" class="btn btn-danger">Cancel Reservation</button>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>


</div>

ValaisBooking/ValaisBooking/Views/Reservation/Index.cshtml
@model DataTransferObject.Reservation

@{
    ViewData["Title"] = "Index";
}


<div>
    <h3 class="text-center mt-5 mb-5">Search my reservation</h3>

    <br /><br />
    <div class="alert alert-danger col-4 mx-auto" asp-validation-summary="ModelOnly">

    </div>

    <form asp-controller="Reservation" asp-action="Index" method="POST" class="col-4 border border-secondary p-4 mx-auto rounded bg-light shadow-lg">
        <div class="form-group">
            <label asp-for="ReservationNumber"></label>
            <input asp-for="ReservationNumber" class="form-control">
            <span asp-validation-for="ReservationNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Firstname"></label>
            <input asp-for="Firstname" class="form-control">
            <span asp-validation-for="Firstname" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Lastname"></label>
            <input asp-for="Lastname" class="form-control">
            <span asp-validation-for="Lastname" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary w-100">Search</button>
    </form>
</div>

ValaisBooking/ValaisBooking/Views/Reservation/PersonDetails.cshtml
@{
    ViewData["Title"] = "PersonDetails";
}

<div>
    <h3 class="text-center mt-5 mb-5">It is your first reservation ? Fill in your personal information !</h3>

    <br /><br />

    <form asp-controller="Reservation" asp-action="PersonSession" method="POST" class="col-4 border border-secondary p-4 mx-auto rounded bg-light shadow-lg">
        <div class="form-group">
            <label>Firstname</label>
            <input type="text" name="firstname" class="form-control">
        </div>
        <div class="form-group">
            <label>Lastname</label>
            <input type="text" name="lastname" class="form-control">
        </div>
        <input type="hidden" name="idRoom" value="@ViewData["idRoom"]" />

        <button type="submit" class="btn btn-primary w-100">Ok</button>
    </form>
</div>